---
# tasks file for RHEL8-CIS
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against RHEL 8. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version_compare('8', '!=')
  tags:
    - always

- name: Check ansible version
  ansible.builtin.fail:
    msg: You must use ansible 2.9 or greater
  when: not ansible_version.full is version_compare('2.9', '>=')
  tags:
    - always

- name: Check crypto-policy input
  ansible.builtin.assert:
    that: rhel8cis_crypto_policy in rhel8cis_allowed_crypto_policies

- name: Check rhel8cis_bootloader_password_hash variable has been changed
  ansible.builtin.assert:
    that: rhel8cis_bootloader_password_hash != 'grub.pbkdf2.sha512.changethispassword'
    msg: "This role will not be able to run single user password commands as rhel8cis_bootloader_password_hash variable has not been set"
  when:
    - rhel8cis_set_boot_pass
    - rhel8cis_rule_1_5_2

- name: "check sugroup exists if used"
  block:
    - name: "Check su group exists if defined"
      ansible.builtin.shell: grep -w "{{ rhel8cis_sugroup }}" /etc/group
      register: sugroup_exists
      changed_when: false
      failed_when: sugroup_exists.rc >= 2
      tags:
        - skip_ansible_lint

    - name: Check sugroup if defined exists before continuing
      ansible.builtin.assert:
        that: sugroup_exists.rc == 0
        msg: "The variable rhel8cis_sugroup is defined but does not exist please rectify"
  when:
    - rhel8cis_sugroup is defined
    - rhel8cis_rule_5_7
  tags:
    - rule_5.7

- ansible.builtin.include: prelim.yml
  become: true
  tags:
    - prelim_tasks
    - always

- import_tasks: pre_remediation_audit.yml
  when:
    - run_audit

- name: Gather the package facts
  package_facts:
    manager: auto
  tags:
    - always

- ansible.builtin.include: parse_etc_password.yml
  become: true
  when: rhel8cis_section6

- ansible.builtin.include: section_1/main.yml
  become: true
  when: rhel8cis_section1
  tags:
    - rhel8cis_section1

- ansible.builtin.include: section_2/main.yml
  become: true
  when: rhel8cis_section2

- ansible.builtin.include: section_3/main.yml
  become: true
  when: rhel8cis_section3

- ansible.builtin.include: section_4/main.yml
  become: true
  when: rhel8cis_section4

- ansible.builtin.include: section_5/main.yml
  become: true
  when: rhel8cis_section5

- ansible.builtin.include: section_6/main.yml
  become: true
  when: rhel8cis_section6

- ansible.builtin.include: post.yml
  become: true
  tags:
    - post_tasks
    - always

- import_tasks: post_remediation_audit.yml
  when:
    - run_audit

- name: Show Audit Summary
  ansible.builtin.debug:
    msg: "{{ audit_results.split('\n') }}"
  when:
    - run_audit
