---
# Post tasks

- name: Perform DNF package cleanup
  ansible.builtin.dnf:
    autoremove: yes
  changed_when: no

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reboot host
  ansible.builtin.reboot:
  when:
    - not rhel8cis_skip_reboot
