---

- name: "3.4.4.1.1 | L1 | PATCH | Ensure iptables default deny firewall policy"
  block:
    - name: "3.4.4.1.1 | L1 |  PATCH |  Ensure iptables default deny firewall policy | Configure ssh to be allowed"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "22"
        jump: ACCEPT

    - name: "3.4.4.1.1 | L1 | PATCH | Ensure iptables default deny firewall policy | Set drop items"
      ansible.builtin.iptables:
        policy: DROP
        chain: "{{ item }}"
      loop:
        - INPUT
        - FORWARD
        - OUTPUT
  when:
    - rhel8cis_rule_3_4_4_1_1
    - rhel8cis_firewall == "iptables"
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_3.4.4.1.1

- name: "3.4.4.1.2 | L1 | PATCH | Ensure iptables loopback traffic is configured"
  block:
    - name: "3.4.4.1.2 | L1 | Ensure iptables loopback traffic is configured | INPUT Loopback ACCEPT"
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: "3.4.4.1.2 | L1 | PATCH | Ensure iptables loopback traffic is configured | OUTPUT Loopback ACCEPT"
      ansible.builtin.iptables:
        action: append
        chain: OUTPUT
        out_interface: lo
        jump: ACCEPT

    - name: "3.4.4.1.2 | L1 | PATCH | Ensure iptables loopback traffic is configured | INPUT Loopback 127.0.0.0/8"
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        source: 127.0.0.0/8
        jump: DROP
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_3.4.4.1.2

- name: "3.4.4.1.3 | L1 | PATCH | Ensure iptables outbound and established connections are configured"
  ansible.builtin.iptables:
    action: append
    chain: '{{ item.chain }}'
    protocol: '{{ item.protocol }}'
    match: state
    ctstate: '{{ item.ctstate }}'
    jump: ACCEPT
  loop:
    - { chain: OUTPUT, protocol: tcp, ctstate: 'NEW,ESTABLISHED' }
    - { chain: OUTPUT, protocol: udp, ctstate: 'NEW,ESTABLISHED' }
    - { chain: OUTPUT, protocol: icmp, ctstate: 'NEW,ESTABLISHED' }
    - { chain: INPUT, protocol: tcp, ctstate: ESTABLISHED }
    - { chain: INPUT, protocol: udp, ctstate: ESTABLISHED }
    - { chain: INPUT, protocol: icmp, ctstate: ESTABLISHED }
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_3
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_3.4.4.1.3

- name: "3.4.4.1.4 | L1 | PATCH | Ensure iptables firewall rules exist for all open ports"
  block:
    - name: "3.4.4.1.4 | L1 | AUDIT | Ensure iptables firewall rules exist for all open ports | Get list of TCP open ports"
      ansible.builtin.shell: netstat -ant |grep "tcp.*LISTEN" | awk '{ print $4 }'| sed 's/.*://'
      changed_when: false
      failed_when: false
      register: rhel8cis_3_4_4_1_4_otcp

    - name: "3.4.4.1.4 | L1 | AUDIT | Ensure iptables firewall rules exist for all open ports | Get the list of udp open ports"
      ansible.builtin.shell: netstat -ant |grep "udp.*LISTEN" | awk '{ print $4 }'| sed 's/.*://'
      changed_when: false
      failed_when: false
      register: rhel8cis_3_4_4_1_4_oudp

    - name: "3.4.4.1.4 | L1 | PATCH | Ensure iptables firewall rules exist for all open ports | Adjust open tcp ports"
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        ctstate: NEW
        jump: ACCEPT
      loop:
        - "{{ rhel8cis_3_4_4_1_4_otcp.stdout_lines }}"
      when: rhel8cis_3_4_4_1_4_otcp.stdout is defined

    - name: "3.4.4.1.4 | L1 | PATCH | Ensure iptables firewall rules exist for all open ports | Adjust open udp ports"
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        protocol: udp
        destination_port: "{{ item }}"
        match: state
        ctstate: NEW
        jump: ACCEPT
      loop:
        - "{{ rhel8cis_3_4_4_1_4_oudp.stdout_lines }}"
      when: rhel8cis_3_4_4_1_4_otcp.stdout is defined
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_3.4.4.1.4

- name: "3.4.4.1.5 | L1 | PATCH | Ensure iptables service is enabled and active | Check if iptables is enabled"
  ansible.builtin.service:
    name: iptables
    enabled: yes
    state: started
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_5
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_3.4.4.1.5
