---

- name: "SECTION | 1.1 | FileSystem Configurations\n
         SECTION | 1.1.1.x | Disable unused filesystems"
  ansible.builtin.include: cis_1.1.1.x.yml
- ansible.builtin.include: cis_1.1.x.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  ansible.builtin.include: cis_1.2.x.yml

- name: "SECTION | 1.3 | Configure sudo"
  ansible.builtin.include: cis_1.3.x.yml

- name: "SECTION | 1.4 | Filesystem Integrity"
  ansible.builtin.include: cis_1.4.x.yml
  when: rhel8cis_config_aide

- name: "SECTION | 1.5 | Secure Boot Settings"
  ansible.builtin.include: cis_1.5.x.yml

- name: "SECTION | 1.6 | Additional Process Hardening"
  ansible.builtin.include: cis_1.6.x.yml

- name: "SECTION | 1.7 | bootloader and Mandatory Access Control"
  ansible.builtin.include: cis_1.7.1.x.yml
  when: not rhel8cis_selinux_disable

- name: "SECTION | 1.8 | Warning Banners"
  ansible.builtin.include: cis_1.8.1.x.yml

- name: "SECTION | 1.9 | Updated and Patches"
  ansible.builtin.include: cis_1.9.yml

- name: "SECTION | 1.10 | Crypto policies"
  ansible.builtin.include: cis_1.10.yml
  when:
    - not system_is_ec2

- name: "SECTION | 1.11 | FIPS/FUTURE Crypto policies"
  ansible.builtin.include: cis_1.11.yml
  when:
    - not system_is_ec2
